config/routes.rb
Badminton::Application.routes.draw do

  get "receber_email/success"
  get "receber_email/password"
  get "receber_email/confirmation"

  get "relatorio/atleta"

  get "relatorio/arbitro"

  get "relatorio/tecnico"

  get "relatorio/arbitros"

  get "relatorio/atletas"

  get "relatorio/tecnicos"

  get "administracao/index"

  devise_for :users, :controllers => { :registrations => :registrations, :passwords => :passwords, :confirmations => :confirmations }

  resources :tecnicos

  resources :arbitros

  resources :atletas

  resources :modalidades

  root :to => 'administracao#index'

end

app/models/modalidade.rb
class Modalidade < ActiveRecord::Base
  attr_accessible :tipo
	has_and_belongs_to_many :atletas
end

app/controllers/modalidades_controller.rb
class ModalidadesController < ApplicationController
  # GET /modalidades
  # GET /modalidades.json
  def index
    @modalidades = Modalidade.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @modalidades }
    end
  end

  # GET /modalidades/1
  # GET /modalidades/1.json
  def show
    @modalidade = Modalidade.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @modalidade }
    end
  end

  # GET /modalidades/new
  # GET /modalidades/new.json
  def new
    @modalidade = Modalidade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @modalidade }
    end
  end

  # GET /modalidades/1/edit
  def edit
    @modalidade = Modalidade.find(params[:id])
  end

  # POST /modalidades
  # POST /modalidades.json
  def create
    @modalidade = Modalidade.new(params[:modalidade])

    respond_to do |format|
      if @modalidade.save
        format.html { redirect_to @modalidade, notice: 'Modalidade was successfully created.' }
        format.json { render json: @modalidade, status: :created, location: @modalidade }
      else
        format.html { render action: "new" }
        format.json { render json: @modalidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /modalidades/1
  # PUT /modalidades/1.json
  def update
    @modalidade = Modalidade.find(params[:id])

    respond_to do |format|
      if @modalidade.update_attributes(params[:modalidade])
        format.html { redirect_to @modalidade, notice: 'Modalidade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @modalidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modalidades/1
  # DELETE /modalidades/1.json
  def destroy
    @modalidade = Modalidade.find(params[:id])
    @modalidade.destroy

    respond_to do |format|
      format.html { redirect_to modalidades_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/modalidades_helper.rb
module ModalidadesHelper
end

app/views/modalidades/_form.html.erb
<%= form_for(@modalidade) do |f| %>
  <% if @modalidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@modalidade.errors.count, "error") %> prohibited this modalidade from being saved:</h2>

      <ul>
      <% @modalidade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/modalidades/edit.html.erb
<h1>Editing modalidade</h1>

<%= render 'form' %>

<%= link_to 'Show', @modalidade %> |
<%= link_to 'Back', modalidades_path %>

app/views/modalidades/index.html.erb
<h1>Listing modalidades</h1>

<table>
  <tr>
    <th>Tipo</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @modalidades.each do |modalidade| %>
  <tr>
    <td><%= modalidade.tipo %></td>
    <td><%= link_to 'Show', modalidade %></td>
    <td><%= link_to 'Edit', edit_modalidade_path(modalidade) %></td>
    <td><%= link_to 'Destroy', modalidade, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Modalidade', new_modalidade_path %>

app/views/modalidades/new.html.erb
<h1>New modalidade</h1>

<%= render 'form' %>

<%= link_to 'Back', modalidades_path %>

app/views/modalidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tipo:</b>
  <%= @modalidade.tipo %>
</p>


<%= link_to 'Edit', edit_modalidade_path(@modalidade) %> |
<%= link_to 'Back', modalidades_path %>