config/routes.rb
Badminton::Application.routes.draw do

  get "receber_email/success"
  get "receber_email/password"
  get "receber_email/confirmation"

  get "relatorio/atleta"

  get "relatorio/arbitro"

  get "relatorio/tecnico"

  get "relatorio/arbitros"

  get "relatorio/atletas"

  get "relatorio/tecnicos"

  get "administracao/index"

  devise_for :users, :controllers => { :registrations => :registrations, :passwords => :passwords, :confirmations => :confirmations }

  resources :tecnicos

  resources :arbitros

  resources :atletas

  resources :modalidades

  root :to => 'administracao#index'

end

app/models/tecnico.rb
class Tecnico < ActiveRecord::Base
  attr_accessible :celular, :cpf, :cref,
  								:data_de_nascimento, :email,
  								:intituicao_de_ensino,
  								:nome, :rg, :telefone, :user_id, :photo, :image_delete,
                  :rua, :numero, :bairro, :cidade, :estado, :cep, :complemento

	belongs_to :user

  validates_presence_of :cpf, :rg, :nome, :data_de_nascimento, :celular, :cref
  validates_uniqueness_of :cpf, :cref

  validates_numericality_of :numero, :greater_than => 0, message: "deve ser maior que zero."

  has_attached_file :photo,
                    :storage => :s3, :s3_credentials => S3_CREDENTIALS,
                    :path => "/system/:class/:id/:style/:basename.:extension"

  validates_attachment_size :photo, :in => 0..100.kilobytes, :message => "deve ser menor do que 100KB"
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

  def self.paginar(param)
    paginate(:page => param, :per_page => 10)
  end

	def self.search(busca)
    where("nome LIKE :termo OR intituicao_de_ensino LIKE :termo OR cref LIKE :termo
    			OR email LIKE :termo", 
          :termo => "%#{busca}%")
  end

  before_save :destroy_image?

  def image_delete
    @image_delete ||= "0"
  end

  def image_delete=(value)
    @image_delete = value
  end

private
  def destroy_image?
    self.photo.clear if @image_delete == "1"
  end
end

app/controllers/tecnicos_controller.rb
# encoding: utf-8
class TecnicosController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /tecnicos
  # GET /tecnicos.json
  def index
    @tecnicos = current_user.tecnicos.scoped
    @tecnicos = @tecnicos.search(params[:search]) if params[:search].present?
    @tecnicos = @tecnicos.paginar(params[:page]).order(:nome)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tecnicos }
      format.xls do
        render :xls => @tecnicos,
                       :columns => [ :nome, :data_de_nascimento, :rg, :cpf, :email, :telefone, :celular,
                                    :rua, :numero, :complemento, :bairro, :cidade, :estado, :cep,
                                    :intituicao_de_ensino, :cref ],
                       :headers => %w[ Nome Data\ de\ Nascimento RG CPF Email Telefone Celular Rua Número Complemento
                                      Bairro Cidade Estado CEP Instituicao\ de\ Ensino CREF ]
      end
    end
  end

  # GET /tecnicos/1
  # GET /tecnicos/1.json
  def show
    @tecnico = Tecnico.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tecnico }
    end
  end

  # GET /tecnicos/new
  # GET /tecnicos/new.json
  def new
    @tecnico = current_user.tecnicos.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tecnico }
    end
  end

  # GET /tecnicos/1/edit
  def edit
    @tecnico = Tecnico.find(params[:id])
  end

  # POST /tecnicos
  # POST /tecnicos.json
  def create
    @tecnico = Tecnico.new(params[:tecnico])
    @tecnico.user = current_user

    respond_to do |format|
      if @tecnico.save
        format.html { redirect_to @tecnico, notice: 'Técnico foi criado com sucesso.' }
        format.json { render json: @tecnico, status: :created, location: @tecnico }
      else
        format.html { render action: "new" }
        format.json { render json: @tecnico.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tecnicos/1
  # PUT /tecnicos/1.json
  def update
    @tecnico = Tecnico.find(params[:id])
    @tecnico.user = current_user

    respond_to do |format|
      if @tecnico.update_attributes(params[:tecnico])
        format.html { redirect_to @tecnico, notice: 'Técnico foi atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tecnico.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tecnicos/1
  # DELETE /tecnicos/1.json
  def destroy
    @tecnico = Tecnico.find(params[:id])
    @tecnico.destroy

    respond_to do |format|
      format.html { redirect_to tecnicos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tecnicos_helper.rb
module TecnicosHelper
end

app/views/tecnicos/_form.html.erb
<%= form_for @tecnico, :html => { :multipart => true} do |f| %>
  <%= error_messages_for @tecnico %>
  <div class="row">
    <div class="span4">
      <h2>Informações do Árbitro</h2>
      <div class="field">
        <b><%= f.label :photo, "Foto:" %></b><br />
        <%= f.file_field :photo %>
      </div>
      <div class="field">
        <%- unless @tecnico.new_record? || !@tecnico.photo? -%>
          <%= image_tag @tecnico.photo.url, :class => "image" %><br />
          <%= f.check_box :image_delete %> <span style="color: #fff">Selecione para apagar a imagem.</span>
        <%- end -%>
      </div>
      <div class="field" style="margin-top: 20px;">
          <%= f.label :intituicao_de_ensino, "Instituição de Ensino" %>
          <%= f.text_field :intituicao_de_ensino %>
        </div>
        <div class="field">
          <%= f.label :cref, "CREF" %>
          <%= f.text_field :cref %>
        </div>
    </div>
    <div class="span4">
      <h2>Informações Pessoais</h2>
      <div class="field">
          <%= f.label :nome %>
          <%= f.text_field :nome, :placeholder => "Nome" %>
        </div>
        <div class="field">
          <%= f.label :data_de_nascimento %>
          <%= f.date_select :data_de_nascimento, :order => [:day, :month, :year], :start_year => 1930,
                            :prompt => { :day => 'Dia', :month => 'Mês', :year => 'Ano' } %>
        </div>
        <div class="field">
          <%= f.label :rg, "RG" %>
          <%= f.text_field :rg, :placeholder => "RG" %>
        </div>
        <div class="field">
          <%= f.label :cpf, "CPF" %>
          <%= f.text_field :cpf, :placeholder => "CPF" %>
        </div>
        <div class="field">
          <%= f.label :email %>
          <%= f.text_field :email, :placeholder => "Email" %>
        </div>
      </div>
      <div class="span4" style="margin-top: 42px;">
        <div class="field">
          <%= f.label :telefone %>
          <%= f.text_field :telefone, :placeholder => "Telefone" %>
        </div>
        <div class="field">
          <%= f.label :celular %>
          <%= f.text_field :celular, :placeholder => "Celular" %>
        </div>
        <div class="field">
          <%= f.label :rua %>
          <%= f.text_field :rua, placeholder: "Rua" %>
        </div>
        <div class="field">
          <%= f.label :numero, "Número" %>
          <%= f.number_field :numero, :min => 0, placeholder: "Número" %>
        </div>
        <div class="field">
          <%= f.label :complemento, "Complemento" %>
          <%= f.text_field :complemento, :placeholder => "Complemento" %>
        </div>
        <div class="field">
          <%= f.label :bairro %>
          <%= f.text_field :bairro, placeholder: "Bairro" %>
        </div>
        <div class="field">
          <%= f.label :cidade %>
          <%= f.text_field :cidade, placeholder: "Cidade" %>
        </div>
        <div class="field">
          <%= f.label :Estado %>
          <%= f.text_field :estado, placeholder: "Estado" %>
        </div>
        <div class="field">
          <%= f.label :cep, "CEP" %>
          <%= f.text_field :cep, placeholder: "CEP" %>
        </div>
    </div>
  </div>
  <br />
  <div class="well">
    <div style="margin-left: 380px;">
      <%= f.submit "Enviar", :class => "btn" %>
    </div>
  </div>
  <%= f.hidden_field :user_id %>
<% end %>

<script type="text/javascript">
jQuery(function($){
   $("#tecnico_cpf").mask("999.999.999-99");
   $("#tecnico_telefone").mask("(99) 9999-9999");
   $("#tecnico_celular").mask("(99) 9999-9999");
   $("#tecnico_cep").mask("99999-999");
});
</script>

app/views/tecnicos/edit.html.erb
<h1>Editando técnico</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @tecnico, :class => "label label-success" %> |
<%= link_to 'Voltar', tecnicos_path, :class => "label label-inverse" %>

app/views/tecnicos/index.html.erb
<h1>Lista de Técnicos</h1>
<div class="well">
    <h2>Busca</h2>
    <%= form_tag tecnicos_path, :method => :get do %>
        <%= search_field_tag :search, "",
                             :placeholder => "Digite sua busca",
                             :class => "input-medium search-query", :style => "width: 400px;" %>
        <%= submit_tag "Buscar", :class => "btn" %> 
    <% end %>
</div>
<% if @tecnicos.empty? %>
<p>Nenhum ténico cadastrado.</p>
<% else %>
<table class="table">
  <tr>
    <th>Nome</th>
    <th>Data de nascimento</th>
    <th>Email</th>
    <th>CREF</th>
    <th>Possui foto?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tecnicos.each do |tecnico| %>
  <tr>
    <td><%= tecnico.nome %></td>
    <td><%= tecnico.data_de_nascimento.strftime("%d/%m/%Y") %></td>
    <td><%= tecnico.email %></td>
    <td><%= tecnico.cref %></td>
    <td>
      <% if tecnico.photo? %>
      <label class="label label-success" style="padding-left: 38px; padding-top: 3px;">SIM</label>
      <% else %>
      <label class="label label-important" style="padding-left: 38px; padding-top: 3px;">NÃO</label>
      <% end -%>
    </td>
    <td><%= link_to 'Exibir', tecnico, :class => "btn btn-primary btn-mini" %></td>
    <td><%= link_to 'Editar', edit_tecnico_path(tecnico), :class => "btn btn-warning btn-mini" %></td>
    <td><%= link_to 'Apagar', tecnico, confirm: 'Você tem certeza?', method: :delete, :class => "btn btn-danger btn-mini" %></td>
  </tr>
<% end %>
</table>
<div style="margin-left: 280px;">
    <%= will_paginate(@tecnicos, :class => "pagination btn-mini", :previous_label => "« Anterior", :next_label => "Próxima »") %>
</div>
<% end -%>
<br />
<%= link_to 'Adicionar Técnico', new_tecnico_path, :class => "label label-info" %> | 
<%= link_to "Exportar para Excel", url_for( :format => :xls ) , :class => "label label-warning" %> | 
<%= link_to "Relatório de Técnicos", relatorio_tecnicos_path, :class => 'btn btn-success' %>

app/views/tecnicos/new.html.erb
<h1>Adicionando técnico</h1>

<%= render 'form' %>

<%= link_to 'Voltar', tecnicos_path, :class => "label label-inverse" %>

app/views/tecnicos/show.html.erb
<%= show_notice(notice) %>
<div class="span10">
  <h1>Informações Detalhadas</h1>
  <div class="row well"> 
    <div class="span4">
      <h2>Informações do Técnico</h2>
      <p>
        <% if @tecnico.photo? %>
          <%= image_tag @tecnico.photo.url, :class => "image" %>
        <% else %>
          <%= image_tag 'no-image.png', :class => "image" %>
        <% end -%>
      </p>
      <p>
        <b>Intituição de ensino:</b>
        <%= @tecnico.intituicao_de_ensino %>
      </p>

      <p>
        <b>CREF:</b>
        <%= @tecnico.cref %>
      </p>
    </div>
    <div class="span5">
      <h2>Informações Pessoais</h2>
      <p>
        <b>Nome:</b>
        <%= @tecnico.nome %>
      </p>

      <p>
        <b>Data de nascimento:</b>
        <%= @tecnico.data_de_nascimento.strftime("%d/%m/%Y") %>
      </p>

      <p>
        <b>Telefone:</b>
        <%= @tecnico.telefone %>
      </p>

      <p>
        <b>Celular:</b>
        <%= @tecnico.celular %>
      </p>

      <p>
        <b>Email:</b>
        <%= @tecnico.email %>
      </p>

      <p>
        <b>Endereço completo:</b>
        <%= "#{@tecnico.rua}, #{@tecnico.numero}, #{@tecnico.bairro}, #{@tecnico.cidade}, #{@tecnico.estado} - #{@tecnico.cep} (#{@tecnico.complemento unless @tecnico.complemento.nil?})" %>
      </p>

      <p>
        <b>RG:</b>
        <%= @tecnico.rg %>
      </p>

      <p>
        <b>CPF:</b>
        <%= @tecnico.cpf %>
      </p>
    </div>
  </div>
  <%= link_to 'Editar', edit_tecnico_path(@tecnico), :class => "label label-warning" %> |
  <%= link_to 'Voltar', tecnicos_path, :class => "label label-inverse" %> | 
  <%= link_to "Relatório detalhado", relatorio_tecnico_path(:id => @tecnico.id), :class => 'btn btn-success' %>
</div>