config/routes.rb
Badminton::Application.routes.draw do

  get "receber_email/success"
  get "receber_email/password"
  get "receber_email/confirmation"

  get "relatorio/atleta"

  get "relatorio/arbitro"

  get "relatorio/tecnico"

  get "relatorio/arbitros"

  get "relatorio/atletas"

  get "relatorio/tecnicos"

  get "administracao/index"

  devise_for :users, :controllers => { :registrations => :registrations, :passwords => :passwords, :confirmations => :confirmations }

  resources :tecnicos

  resources :arbitros

  resources :atletas

  resources :modalidades

  root :to => 'administracao#index'

end

app/models/arbitro.rb
class Arbitro < ActiveRecord::Base
  attr_accessible :ano_do_curso_de_arbitragem, :cpf, :cursos_de_arbitragem,
  								:data_de_nascimento, :email, :nome, :rg,
  								:telefone, :celular, :user_id, :photo, :image_delete,
                  :rua, :numero, :bairro, :cidade, :estado, :cep, :complemento

	belongs_to :user

	validates_presence_of :cpf, :rg, :data_de_nascimento, :nome, :celular, :ano_do_curso_de_arbitragem
	validates_uniqueness_of :cpf
  validates_numericality_of :numero, :greater_than => 0, :message => "deve ser maior que zero."

	has_attached_file :photo,
                    :storage => :s3, :s3_credentials => S3_CREDENTIALS,
                    :path => "/system/:class/:id/:style/:basename.:extension"

  validates_attachment_size :photo, :in => 0..100.kilobytes, :message => "deve ser menor do que 100KB"
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

	def self.paginar(param)
		paginate(:page => param, :per_page => 10)
	end

	def self.search(busca)
    where("nome LIKE :termo OR celular LIKE :termo OR cpf LIKE :termo", :termo => "%#{busca}%")
  end

  before_save :destroy_image?

  def image_delete
    @image_delete ||= "0"
  end

  def image_delete=(value)
    @image_delete = value
  end

private
  def destroy_image?
    self.photo.clear if @image_delete == "1"
  end
end

app/controllers/arbitros_controller.rb
# encoding: utf-8
class ArbitrosController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource
  # GET /arbitros
  # GET /arbitros.json
  def index
    @arbitros = current_user.arbitros.scoped
    @arbitros = @arbitros.search(params[:search]) if params[:search].present?
    @arbitros = @arbitros.paginar(params[:page]).order(:nome)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @arbitros }
      format.xls do
        render :xls => @arbitros,
                       :columns => [ :nome, :data_de_nascimento, :rg, :cpf, :email, :telefone, :celular,
                                    :rua, :numero, :complemento, :bairro, :cidade, :estado, :cep,
                                    :ano_do_curso_de_arbitragem, :cursos_de_arbitragem ],
                       :headers => %w[ Nome Data\ de\ Nascimento RG CPF Email Telefone Celular 
                                      Rua Número Complemento Bairro Cidade Estado CEP
                                      Ano\ do\ Curso\ de\ Arbitragem Cursos\ de\ Arbitragem ]
      end
    end
  end

  # GET /arbitros/1
  # GET /arbitros/1.json
  def show
    @arbitro = Arbitro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @arbitro }
    end
  end

  # GET /arbitros/new
  # GET /arbitros/new.json
  def new
    @arbitro = current_user.arbitros.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @arbitro }
    end
  end

  # GET /arbitros/1/edit
  def edit
    @arbitro = Arbitro.find(params[:id])
  end

  # POST /arbitros
  # POST /arbitros.json
  def create
    @arbitro = Arbitro.new(params[:arbitro])
    @arbitro.user = current_user

    respond_to do |format|
      if @arbitro.save
        format.html { redirect_to @arbitro, notice: 'Árbitro foi criado com sucesso.' }
        format.json { render json: @arbitro, status: :created, location: @arbitro }
      else
        format.html { render action: "new" }
        format.json { render json: @arbitro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /arbitros/1
  # PUT /arbitros/1.json
  def update
    @arbitro = Arbitro.find(params[:id])
    @arbitro.user = current_user

    respond_to do |format|
      if @arbitro.update_attributes(params[:arbitro])
        format.html { redirect_to @arbitro, notice: 'Árbitro foi atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @arbitro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arbitros/1
  # DELETE /arbitros/1.json
  def destroy
    @arbitro = Arbitro.find(params[:id])
    @arbitro.destroy

    respond_to do |format|
      format.html { redirect_to arbitros_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/arbitros_helper.rb
module ArbitrosHelper
end

app/views/arbitros/_form.html.erb
<%= form_for @arbitro, :html => { :multipart => true } do |f| %>
  <%= error_messages_for @arbitro %>
  <div class="row">
    <div class="span4">
      <h2>Informações do Árbitro</h2>
      <div class="field">
        <b><%= f.label :photo, "Foto:" %></b><br />
        <%= f.file_field :photo %>
      </div>
      <div class="field">
        <%- unless @arbitro.new_record? || !@arbitro.photo? -%>
          <%= image_tag @arbitro.photo.url, :class => "image" %>
          <%= f.check_box :image_delete %> <span style="color: #fff">Selecione para apagar a imagem.</span>
        <%- end -%>
      </div>
      <div class="field" style="margin-top: 20px;">
        <%= f.label :cursos_de_arbitragem %>
        <%= f.text_area :cursos_de_arbitragem, :cols => 80, :rows => 10 %>
      </div>
      <div class="field">
        <%= f.label :ano_do_curso_de_arbitragem %>
        <%= f.date_select :ano_do_curso_de_arbitragem, :discard_day => true, :discard_month => true,
                          :start_year => 1930,
                          :prompt => { :year => 'Selecione o ano' } %>
      </div>
    </div>
    <div class="span4">
      <h2>Informações Pessoais</h2>
      <div class="field">
        <%= f.label :nome %>
        <%= f.text_field :nome %>
      </div>
      <div class="field">
        <%= f.label :data_de_nascimento %>
        <%= f.date_select(:data_de_nascimento, :start_year => 1930,
                              :prompt => { :day => 'Dia', :month => 'Mês', :year => 'Ano' },
                              :order => [:day, :month, :year]) %>
      </div>
      <div class="field">
        <%= f.label :rg, "RG" %>
        <%= f.text_field :rg %>
      </div>
      <div class="field">
        <%= f.label :cpf, "CPF" %>
        <%= f.text_field :cpf %>
      </div>
      <div class="field">
        <%= f.label :email %>
        <%= f.text_field :email %>
      </div>
    </div>
    <div class="span4" style="margin-top: 42px;">
      <div class="field">
        <%= f.label :telefone %>
        <%= f.text_field :telefone %>
      </div>
      <div class="field">
        <%= f.label :celular %>
        <%= f.text_field :celular %>
      </div>
      <div class="field">
        <%= f.label :rua %>
        <%= f.text_field :rua, placeholder: "Rua" %>
      </div>
      <div class="field">
        <%= f.label :numero, "Número" %>
        <%= f.number_field :numero, min: 0, placeholder: "Número" %>
      </div>
      <div class="field">
        <%= f.label :complemento, "Complemento" %>
        <%= f.text_field :complemento, :placeholder => "Complemento" %>
      </div>
      <div class="field">
        <%= f.label :bairro %>
        <%= f.text_field :bairro, placeholder: "Bairro" %>
      </div>
      <div class="field">
        <%= f.label :cidade %>
        <%= f.text_field :cidade, placeholder: "Cidade" %>
      </div>
      <div class="field">
        <%= f.label :estado %>
        <%= f.text_field :estado, placeholder: "Estado" %>
      </div>
      <div class="field">
        <%= f.label :cep, "CEP" %>
        <%= f.text_field :cep, placeholder: "CEP" %>
      </div>
    </div>
  </div>
  <br />
  <div class="well">
    <div style="margin-left: 380px;">
      <%= f.submit "Enviar", :class => "btn" %>
    </div>
  </div>
  <%= f.hidden_field :user_id %>
<% end %>

<script type="text/javascript">
jQuery(function($){
   $("#arbitro_cpf").mask("999.999.999-99");
   $("#arbitro_telefone").mask("(99) 9999-9999");
   $("#arbitro_celular").mask("(99) 9999-9999");
   $("#arbitro_cep").mask("99999-999");
});
</script>

app/views/arbitros/edit.html.erb
<h1>Editando Árbitro</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @arbitro, :class => "label label-success" %> |
<%= link_to 'Voltar', arbitros_path, :class => "label label-inverse" %>

app/views/arbitros/index.html.erb
<h1>Lista de Árbitros</h1>
<div class="well">
    <h2>Busca</h2>
    <%= form_tag arbitros_path, :method => :get do %>
        <%= search_field_tag :search, "",
                             :placeholder => "Digite sua busca",
                             :class => "input-large search-query", :style => "width: 400px;" %>
        <%= submit_tag "Buscar", :class => "btn" %> 
    <% end %>
</div>
<% if @arbitros.empty? %>
<p>Nenhum árbitro cadastrado.</p>
<% else %>
<table class="table">
  <tr>
    <th>Nome</th>
    <th>Data de nascimento</th>
    <th>Email</th>
    <th>Celular</th>
    <th>Possui foto?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @arbitros.each do |arbitro| %>
  <tr>
    <td><%= arbitro.nome %></td>
    <td><%= arbitro.data_de_nascimento.strftime("%d/%m/%Y") %></td>
    <td><%= arbitro.email %></td>
    <td><%= arbitro.celular %></td>
    <td>
      <% if arbitro.photo? %>
      <label class="label label-success" style="padding-left: 22px; padding-top: 3px;">SIM</label>
      <% else %>
      <label class="label label-important" style="padding-left: 22px; padding-top: 3px;">NÃO</label>
      <% end -%>
    </td>
    <td><%= link_to 'Exibir', arbitro, :class => "btn btn-primary btn-mini" %></td>
    <td><%= link_to 'Editar', edit_arbitro_path(arbitro), :class => "btn btn-warning btn-mini" %></td>
    <td><%= link_to 'Apagar', arbitro, confirm: 'Você tem certeza?', method: :delete, :class => "btn btn-danger btn-mini" %></td>
  </tr>
<% end %>
</table>
<div class="offset4">
    <%= will_paginate(@arbitros, :class => "pagination btn-mini", :previous_label => "« Anterior", :next_label => "Próxima »") %>
</div>
<% end -%>
<br />
<%= link_to 'Adicionar Árbitro', new_arbitro_path, :class => "label label-info" %> | 
<%= link_to "Exportar para Excel", url_for( :format => :xls ) , :class => "label label-warning" %> | 
<%= link_to "Relatório de Árbitros", relatorio_arbitros_path, :class => 'btn btn-success' %>

app/views/arbitros/new.html.erb
<h1>Adicionar Árbitro</h1>

<%= render 'form' %>

<%= link_to 'Voltar', arbitros_path, :class => "label label-inverse" %>

app/views/arbitros/show.html.erb
<%= show_notice(notice) %>
<div class="span10">
  <h1>Informações Detalhadas</h1>
  <div class="row well"> 
    <div class="span4">
      <h2>Informações do Árbitro</h2>
      <p>
        <% if @arbitro.photo? %>
          <%= image_tag @arbitro.photo.url , :class => "image" %>
        <% else %>
          <%= image_tag "no-image.png", :class => "image" %>
        <% end -%>
      </p>
      <p>
        <b>Cursos de arbitragem:</b>
        <%= @arbitro.cursos_de_arbitragem %>
      </p>

      <p>
        <b>Ano do curso de arbitragem:</b>
        <%= @arbitro.ano_do_curso_de_arbitragem.strftime("%Y") %>
      </p>
    </div>
    <div class="span5">
      <h2>Informações Pessoais</h2>
      <p>
        <b>Nome:</b>
        <%= @arbitro.nome %>
      </p>

      <p>
        <b>Data de nascimento:</b>
        <%= @arbitro.data_de_nascimento.strftime("%d/%m/%Y") %>
      </p>

      <p>
        <b>Email:</b>
        <%= @arbitro.email %>
      </p>

      <p>
        <b>Telefone:</b>
        <%= @arbitro.telefone %>
      </p>

      <p>
        <b>Celular:</b>
        <%= @arbitro.celular %>
      </p>

      <p>
        <b>Endereço completo:</b>
        <%= "#{@arbitro.rua}, #{@arbitro.numero}, #{@arbitro.bairro}, #{@arbitro.cidade}, #{@arbitro.estado} - #{@arbitro.cep} (#{@arbitro.complemento unless @arbitro.complemento.nil?})" %>
      </p>

      <p>
        <b>RG:</b>
        <%= @arbitro.rg %>
      </p>

      <p>
        <b>CPF:</b>
        <%= @arbitro.cpf %>
      </p>
  </div>
</div>

<%= link_to 'Editar', edit_arbitro_path(@arbitro), :class => "label label-warning" %> |
<%= link_to 'Voltar', arbitros_path, :class => "label label-inverse" %> | 
<%= link_to "Relatório detalhado", relatorio_arbitro_path(:id => @arbitro.id), :class => 'btn btn-success' %>
</div>