config/routes.rb
Badminton::Application.routes.draw do

  get "receber_email/success"
  get "receber_email/password"
  get "receber_email/confirmation"

  get "relatorio/atleta"

  get "relatorio/arbitro"

  get "relatorio/tecnico"

  get "relatorio/arbitros"

  get "relatorio/atletas"

  get "relatorio/tecnicos"

  get "administracao/index"

  devise_for :users, :controllers => { :registrations => :registrations, :passwords => :passwords, :confirmations => :confirmations }

  resources :tecnicos

  resources :arbitros

  resources :atletas

  resources :modalidades

  root :to => 'administracao#index'

end

app/models/atleta.rb
class Atleta < ActiveRecord::Base
  attr_accessible :categoria, :codigo, :cpf,
  								:data_de_nascimento, :email,
  								:entidade_filiada,
  								:nome, :nome_da_mae, :nome_do_pai,
  								:ranking, :rg, :modalidade_ids,
  								:celular, :telefone,
  								:user_id, :photo, :image_delete,
                  :rua, :numero, :bairro, :cidade, :estado, :cep, :complemento
  								
	has_and_belongs_to_many :modalidades

	belongs_to :user

  validates_presence_of :codigo, :nome, :cpf, :rg,
                        :data_de_nascimento, :email,
                        :nome_da_mae, :celular

  validates_uniqueness_of :cpf, :email

  validates_numericality_of :numero, :greater_than => 0, :message => "deve ser maior que zero."

  has_attached_file :photo,
                    :storage => :s3, :s3_credentials => S3_CREDENTIALS,
                    :path => "/system/:class/:id/:style/:basename.:extension"

  validates_attachment_size :photo, :in => 0..100.kilobytes, :message => "deve ser menor do que 100KB"
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']                    

  def self.paginar(param)
    paginate(:page => param, :per_page => 10)
  end

  def self.search(busca)
    where("nome LIKE :termo OR nome_da_mae LIKE :termo OR nome_do_pai LIKE :termo OR codigo LIKE :termo", 
          :termo => "%#{busca}%")
  end

  before_save :destroy_image?

  def image_delete
    @image_delete ||= "0"
  end

  def image_delete=(value)
    @image_delete = value
  end

private
  def destroy_image?
    self.photo.clear if @image_delete == "1"
  end
end

app/controllers/atletas_controller.rb
# encoding: utf-8
class AtletasController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_resouces, :only => %w(new create edit update)
  load_and_authorize_resource

  # GET /atletas
  # GET /atletas.json
  def index

    @atletas = current_user.atletas.scoped
    @atletas = @atletas.search(params[:search]) if params[:search].present?
    @atletas = @atletas.paginar(params[:page]).order(:nome)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @atletas }
      format.xls do
        render :xls => @atletas,
                       :columns => [ :nome, :data_de_nascimento, :nome_do_pai, :nome_da_mae, :rg, :cpf, :email, :telefone, :celular,
                                    :rua, :numero, :complemento, :bairro, :cidade, :estado, :cep,
                                    :codigo, :entidade_filiada, :ranking, :categoria ],
                       :headers => %w[ Nome Data\ de\ Nascimento Nome\ do\ Pai Nome\ da\ Mãe RG CPF Email Telefone Celular 
                                      Rua Número Complemento Bairro Cidade Estado CEP
                                      Código Entidade\ Filiada Ranking Categoria ]
      end
    end
  end

  # GET /atletas/1
  # GET /atletas/1.json
  def show
    @atleta = Atleta.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @atleta }
    end
  end

  # GET /atletas/new
  # GET /atletas/new.json
  def new
    @atleta = current_user.atletas.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @atleta }
    end
  end

  # GET /atletas/1/edit
  def edit
    @atleta = Atleta.find(params[:id])
  end

  # POST /atletas
  # POST /atletas.json
  def create
    @atleta = Atleta.new(params[:atleta])
    @atleta.user = current_user

    respond_to do |format|
      if @atleta.save
        format.html { redirect_to @atleta, notice: 'Atleta foi criado com sucesso.' }
        format.json { render json: @atleta, status: :created, location: @atleta }
      else
        format.html { render action: "new" }
        format.json { render json: @atleta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /atletas/1
  # PUT /atletas/1.json
  def update
    @atleta = Atleta.find(params[:id])
    @atleta.user = current_user

    respond_to do |format|
      if @atleta.update_attributes(params[:atleta])
        format.html { redirect_to @atleta, notice: 'Atleta foi atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @atleta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atletas/1
  # DELETE /atletas/1.json
  def destroy
    @atleta = Atleta.find(params[:id])
    @atleta.destroy

    respond_to do |format|
      format.html { redirect_to atletas_url }
      format.json { head :no_content }
    end
  end

protected
  def load_resouces
    @modalidades = Modalidade.all
    @categorias = %w{SUB-10 SUB-11 SUB-13 SUB-15 SUB-17 SUB-19 Principal Sênior Veterano}
  end

end

app/helpers/atletas_helper.rb
module AtletasHelper
end

app/views/atletas/_form.html.erb
<%= form_for @atleta, :html => { :multipart => true} do |f| %>
  <%= error_messages_for @atleta %>

  <div class="row">
    <div class="span4">
      <h2>Informações do Atleta</h2>
      <div class="field">
        <b><%= f.label :photo, "Foto:" %></b><br />
        <%= f.file_field :photo %>
      </div>
      <div class="field">
        <%- unless @atleta.new_record? || !@atleta.photo? -%>
          <%= image_tag @atleta.photo.url, :class => "image" %>
          <%= f.check_box :image_delete %> <span style="color: #fff">Selecione para apagar a imagem.</span>
        <%- end -%>
      </div>
      <div class="field" style="margin-top: 20px;">
        <%= f.label :codigo, "Código*" %>
        <%= f.text_field :codigo, :placeholder => "Código" %>
      </div>
      <div class="field">
        <%= f.label :entidade_filiada %>
        <%= f.text_field :entidade_filiada, :placeholder => "Entidade Filiada" %>
      </div>
      <div class="field">
        <%= f.label :ranking %>
        <%= f.number_field :ranking, :placeholder => "Ranking" %>
      </div>
      <div class="field">
        <%= f.label :categoria %>
        <%= f.select(:categoria, @categorias,
                     :prompt => "Selecione a categoria") %>
      </div>
      <div class="field">
        <%= f.label "Modalidade" %>
        <ul>
          <% @modalidades.each do |m| %>
            <li><%= check_box_tag "atleta[modalidade_ids][]", m.id, @atleta.modalidades.include?(m) %> <%= m.tipo %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="span4">
      <h2>Informações Pessoais</h2>
      <div class="field">
        <%= f.label :nome, "Nome*" %>
        <%= f.text_field :nome, :placeholder => "Nome" %>
      </div>
      <div class="row-fluid">
        <div class="span5">
          <%= f.label :data_de_nascimento, "Data de nascimento*" %>
          <%= f.date_select(:data_de_nascimento, :start_year => 70.years.ago.year, :end_year => Date.today.year,
                            :prompt => { :day => 'Dia', :month => 'Mês', :year => 'Ano' },
                            :order => [:day, :month, :year]) %></div>
      </div>
      <div class="field">
        <%= f.label :nome_do_pai %>
        <%= f.text_field :nome_do_pai, :placeholder => "Nome do pai" %>
      </div>
      <div class="field">
        <%= f.label :nome_da_mae, "Nome da mãe*" %>
        <%= f.text_field :nome_da_mae, :placeholder => "Nome da mãe" %>
      </div>
      <div class="field">
        <%= f.label :email, "Email*" %>
        <%= f.text_field :email, :placeholder => "Email" %>
      </div>
      <div class="field">
        <%= f.label :rg, "RG*" %>
        <%= f.text_field :rg, :placeholder => "RG" %>
      </div>
      <div class="field">
        <%= f.label :cpf, "CPF*" %>
        <%= f.text_field :cpf, :placeholder => "CPF" %>
      </div>
      <div class="field">
        <%= f.label :telefone %>
        <%= f.text_field :telefone, :placeholder => "Telefone" %>
      </div>
      <div class="field">
        <%= f.label :celular, "Celular*" %>
        <%= f.text_field :celular, :placeholder => "Celular" %>
      </div>
    </div>
    <div class="span4">
      <h2>Endereço</h2>
      <div class="field">
        <%= f.label :rua, "Rua" %>
        <%= f.text_field :rua, :placeholder => "Rua" %>
      </div>
      <div class="field">
        <%= f.label :numero, "Número" %>
        <%= f.number_field :numero, :min => 0, :placeholder => "Número" %>
      </div>
      <div class="field">
        <%= f.label :complemento, "Complemento" %>
        <%= f.text_field :complemento, :placeholder => "Complemento" %>
      </div>
      <div class="field">
        <%= f.label :bairro, "Bairro" %>
        <%= f.text_field :bairro, :placeholder => "Bairro" %>
      </div>
      <div class="field">
        <%= f.label :cidade %>
        <%= f.text_field :cidade, :placeholder => "Cidade" %>
      </div>
      <div class="field">
        <%= f.label :estado %>
        <%= f.text_field :estado, :placeholder => "Estado" %>
      </div>
      <div class="field">
        <%= f.label :cep, "CEP" %>
        <%= f.text_field :cep, :placeholder => "CEP" %>
      </div>
    </div>
  </div>
  <br />
  <div class="well">
    <div style="margin-left: 380px;">
      <%= f.submit "Enviar", :class => "btn" %>
    </div>
  </div>
  <%= f.hidden_field :user_id %>
<% end %>

<script type="text/javascript">
jQuery(function($){
   $("#atleta_cpf").mask("999.999.999-99");
   $("#atleta_telefone").mask("(99) 9999-9999");
   $("#atleta_celular").mask("(99) 9999-9999");
   $("#atleta_cep").mask("99999-999");
});
</script>

app/views/atletas/edit.html.erb
<h1>Editando Atleta</h1>

<%= render 'form' %>

<%= link_to 'Exibir', @atleta, :class => "label label-success" %> |
<%= link_to 'Voltar', atletas_path, :class => "label label-inverse" %>

app/views/atletas/index.html.erb
<h1>Lista de Atletas</h1>
<div class="well">
    <h2>Busca</h2>
    <%= form_tag atletas_path, :method => :get do %>
        <%= search_field_tag :search, "",
                             :placeholder => "Digite sua busca",
                             :class => "input-medium search-query", :style => "width: 400px;" %>
        <%= submit_tag "Buscar", :class => "btn" %> 
    <% end %>
</div>
<% if @atletas.empty? %>
<p>Nenhum atleta cadastrado.</p>
<% else %>
<table class="table">
  <tr>
    <th>Código</th>
    <th>Nome</th>
    <th>Data de Nascimento</th>
    <th>Celular</th>
    <th>Nome da mãe</th>
    <th>Possui foto?</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @atletas.each do |atleta| %>
  <tr>
    <td><%= atleta.codigo %></td>
    <td><%= atleta.nome %></td>
    <td><%= atleta.data_de_nascimento.strftime("%d/%m/%Y") %></td>
    <td><%= atleta.celular %></td>
    <td><%= atleta.nome_da_mae %></td>
    <td>
      <% if atleta.photo? %>
      <label class="label label-success" style="padding-left: 35px; padding-top: 3px;">SIM</label>
      <% else %>
      <label class="label label-important" style="padding-left: 35px; padding-top: 3px;">NÃO</label>
      <% end -%>
    </td>
    <td><%= link_to 'Exibir', atleta, :class => "btn btn-primary btn-mini" %></td>
    <td><%= link_to 'Editar', edit_atleta_path(atleta), :class => "btn btn-warning btn-mini" %></td>
    <td><%= link_to 'Apagar', atleta, confirm: 'Você tem certeza?', method: :delete, :class => "btn btn-danger btn-mini" %></td>
  </tr>
<% end %>
</table>
<div class="offset4">
    <%= will_paginate(@atletas, :class => "pagination btn-mini", :previous_label => "« Anterior", :next_label => "Próxima »") %>
</div>
<% end %>
<br />
<div>
    <p>
      <%= link_to 'Adicionar Atleta', new_atleta_path,  :class => "label label-info" %> | 
      <%= link_to "Exportar para Excel", url_for( :format => :xls ) , :class => "label label-warning" %> | 
      <%= link_to "Relatório de Atletas", relatorio_atletas_path, :class => 'btn btn-success' %>
    </p>
</div>

app/views/atletas/new.html.erb
<h1>Adicionando atleta</h1>

<%= render 'form' %>

<%= link_to 'Voltar', atletas_path, :class => "label label-inverse" %>

app/views/atletas/show.html.erb
<%= show_notice(notice) %>
<div class="span10">
  <h1>Informações Detalhadas</h1>
  <div class="row well"> 
    <div class="span4">
      <h2>Informações do Atleta</h2>
      <p>
        <% if @atleta.photo? %>
          <%= image_tag @atleta.photo.url , :class => "image" %>
        <% else %>
          <%= image_tag "no-image.png", :class => "image" %>
        <% end -%>
      </p>
      <p>
        <b>Código:</b>
        <%= @atleta.codigo %>
      </p>
      <p>
        <b>Entidade filiada:</b>
        <%= @atleta.entidade_filiada %>
      </p>

      <p>
        <b>Ranking:</b>
        <%= @atleta.ranking %>
      </p>

      <p>
        <b>Categoria:</b>
        <%= @atleta.categoria %>
      </p>

      <p>
        <b>Modalidades:</b><br />
        <ul>
        <% @atleta.modalidades.each do |mod| %>
          <li><%= mod.tipo %></li>
        <% end -%>
        </ul>
      </p>
    </div>
    <div class="span5">
      <h2>Informações Pessoais</h2>
      <p>
        <b>Nome:</b>
        <%= @atleta.nome %>
      </p>

      <p>
        <b>Telefone:</b>
        <%= @atleta.telefone %>
      </p>

      <p>
        <b>Celular:</b>
        <%= @atleta.celular %>
      </p>

      <p>
        <b>Email:</b>
        <%= @atleta.email %>
      </p>

      <p>
        <b>Data de nascimento:</b>
        <%= @atleta.data_de_nascimento.strftime("%d/%m/%Y") %>
      </p>

      <p>
        <b>Endereço completo:</b>
        <%= "#{@atleta.rua}, #{@atleta.numero}, #{@atleta.bairro}, #{@atleta.cidade}, #{@atleta.estado} - #{@atleta.cep} (#{@atleta.complemento unless @atleta.complemento.nil?})" %>
      </p>

      <p>
        <b>RG:</b>
        <%= @atleta.rg %>
      </p>

      <p>
        <b>CPF:</b>
        <%= @atleta.cpf %>
      </p>

      <p>
        <b>Nome do pai:</b>
        <%= @atleta.nome_do_pai %>
      </p>

      <p>
        <b>Nome da mãe:</b>
        <%= @atleta.nome_da_mae %>
      </p>
    </div>
  </div>
  <%= link_to 'Editar', edit_atleta_path(@atleta), :class => "label label-warning" %> |
  <%= link_to 'Voltar', atletas_path, :class => "label label-inverse" %> | 
  <%= link_to "Relatório detalhado", relatorio_atleta_path(:id => @atleta.id), :class => "btn btn-success"  %>
  </div>
</div>